language: php

php:
 - 7.2

before_script:
  - composer require --no-interaction php-coveralls/php-coveralls
  - composer install --no-interaction --prefer-dist
  - mkdir -p build/logs/

script:
  - php vendor/bin/kahlan --cc=true --coverage=4 --clover=build/logs/clover.xml

after_success:
  - php vendor/bin/php-coveralls -v
